
spring:
  datasource:
    username: root
    password: '#Nivi125128'
    url: jdbc:mysql://localhost:3306/hotel_db
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

